version: "2"

run:
  timeout: 5m

issues:
  max-same-issues: 50

formatters:
  enable:
    - goimports
    - gofumpt
  settings:
    goimports:
      local-prefixes:
        - github.com/ahmad/migrate

linters:
  default: standard
  enable:
    # Error handling
    - errorlint
    - nilerr
    - wrapcheck

    # Correctness
    - bodyclose
    - noctx
    - durationcheck
    - makezero
    - copyloopvar

    # Code quality
    - gocritic
    - revive
    - exhaustive
    - nestif
    - nakedret
    - unconvert
    - unparam
    - wastedassign

    # Performance
    - perfsprint

    # Security
    - gosec

    # Complexity
    - cyclop
    - gocognit
    - funlen

    # Style
    - godot
    - nolintlint
    - usestdlibvars
    - goconst
    - predeclared

    # Test quality
    - testifylint
    - tparallel

  settings:
    cyclop:
      max-complexity: 15
      package-average: 7.0

    gocognit:
      min-complexity: 20

    funlen:
      lines: 80
      statements: 40

    wrapcheck:
      ignore-package-globs:
        - github.com/ahmad/migrate/*

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
        - opinionated

    revive:
      rules:
        - name: exported
          arguments: ["checkPrivateReceivers", "sayRepetitiveInsteadOfStutters"]
        - name: var-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: unused-parameter

    exhaustive:
      default-signifies-exhaustive: false
      check:
        - switch
        - map

    nakedret:
      max-func-lines: 5

    gosec:
      severity: medium
      confidence: medium

    nestif:
      min-complexity: 5

    goconst:
      min-len: 3
      min-occurrences: 3

    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false

  exclusions:
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      - path: "_test\\.go$"
        linters:
          - wrapcheck
          - gosec
          - funlen
          - goconst
          - noctx
          - errcheck
          - gochecknoglobals
          - dupl
      - path: "cmd/"
        linters:
          - gochecknoglobals
          - gochecknoinits
