profile: coverage.out

threshold:
  file: 70
  package: 75
  total: 80

exclude:
  paths:
    - cmd/.*\/main\.go$
    - \.pb\.go$

override:
  - path: internal/analyzer/rules/.*\.go
    threshold: 90
  - path: internal/executor/.*\.go
    threshold: 85
  - path: internal/database/.*\.go
    threshold: 0
  - path: internal/tracker/tracker\.go
    threshold: 0
